-- Region / segment access control — apply as AOP_OWNER after base DDL
-- Adds regional and segment scoping for all audit windows.

ALTER TABLE audit_reports ADD region VARCHAR2(50) DEFAULT 'CENTRAL' NOT NULL;
ALTER TABLE audit_reports ADD segment VARCHAR2(50) DEFAULT 'BRANCH_AUDIT' NOT NULL;
ALTER TABLE observations ADD region VARCHAR2(50) DEFAULT 'CENTRAL' NOT NULL;
ALTER TABLE observations ADD segment VARCHAR2(50) DEFAULT 'BRANCH_AUDIT' NOT NULL;

ALTER TABLE audit_reports ADD CONSTRAINT ck_reports_region
  CHECK (region IN ('NORTH','SOUTH','CENTRAL'));
ALTER TABLE audit_reports ADD CONSTRAINT ck_reports_segment
  CHECK (segment IN ('BRANCH_AUDIT','SHARIAH','MANAGEMENT','OTHER'));
ALTER TABLE observations ADD CONSTRAINT ck_obs_region
  CHECK (region IN ('NORTH','SOUTH','CENTRAL'));
ALTER TABLE observations ADD CONSTRAINT ck_obs_segment
  CHECK (segment IN ('BRANCH_AUDIT','SHARIAH','MANAGEMENT','OTHER'));

CREATE INDEX ix_reports_region ON audit_reports(region) TABLESPACE aop_index;
CREATE INDEX ix_reports_segment ON audit_reports(segment) TABLESPACE aop_index;
CREATE INDEX ix_obs_region ON observations(region) TABLESPACE aop_index;
CREATE INDEX ix_obs_segment ON observations(segment) TABLESPACE aop_index;
CREATE INDEX ix_obs_region_segment ON observations(region, segment) TABLESPACE aop_index;

CREATE TABLE user_regions (
    id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  NUMBER NOT NULL,
    region   VARCHAR2(50) NOT NULL,
    CONSTRAINT uk_user_region UNIQUE (user_id, region),
    CONSTRAINT fk_user_regions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT ck_user_regions_region CHECK (region IN ('NORTH','SOUTH','CENTRAL'))
) TABLESPACE aop_data;

CREATE INDEX ix_user_regions_user ON user_regions(user_id) TABLESPACE aop_index;
CREATE INDEX ix_user_regions_region ON user_regions(region) TABLESPACE aop_index;

CREATE TABLE user_segments (
    id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  NUMBER NOT NULL,
    segment  VARCHAR2(50) NOT NULL,
    CONSTRAINT uk_user_segment UNIQUE (user_id, segment),
    CONSTRAINT fk_user_segments_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT ck_user_segments_segment CHECK (segment IN ('BRANCH_AUDIT','SHARIAH','MANAGEMENT','OTHER'))
) TABLESPACE aop_data;

CREATE INDEX ix_user_segments_user ON user_segments(user_id) TABLESPACE aop_index;
CREATE INDEX ix_user_segments_segment ON user_segments(segment) TABLESPACE aop_index;

GRANT SELECT, INSERT, UPDATE, DELETE ON user_regions TO aop_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON user_segments TO aop_app;
-- Runtime DELETE is allowed only on assignment tables so admins can revoke access.
