-- =============================================================================
-- AOP Oracle DDL — run as AOP_OWNER after oracle_provision.sql
-- Target: Oracle 19c+ / XE 21c
-- Objects live in AOP_OWNER; runtime access is granted to AOP_APP only.
-- =============================================================================

-- USERS
CREATE TABLE users (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR2(100) NOT NULL,
    email           VARCHAR2(255) NOT NULL,
    full_name       VARCHAR2(255) NOT NULL,
    hashed_password VARCHAR2(255),
    role            VARCHAR2(50)  NOT NULL,
    department      VARCHAR2(255),
    is_active       NUMBER(1) DEFAULT 1 NOT NULL,
    ldap_dn         VARCHAR2(500),
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN','CENTRAL_TEAM','PROCESS_OWNER','AUDITOR','VIEWER')),
    CONSTRAINT ck_users_active CHECK (is_active IN (0,1))
) TABLESPACE aop_data;

CREATE INDEX ix_users_role ON users(role) TABLESPACE aop_index;
CREATE INDEX ix_users_active ON users(is_active) TABLESPACE aop_index;

-- AUDIT REPORTS
CREATE TABLE audit_reports (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR2(500) NOT NULL,
    report_number   VARCHAR2(100) NOT NULL,
    description     CLOB,
    file_name       VARCHAR2(500),
    file_path       VARCHAR2(1000),
    uploaded_by_id  NUMBER NOT NULL,
    audit_date      TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_reports_number UNIQUE (report_number),
    CONSTRAINT fk_reports_uploader FOREIGN KEY (uploaded_by_id) REFERENCES users(id)
) TABLESPACE aop_data;

CREATE INDEX ix_reports_uploader ON audit_reports(uploaded_by_id) TABLESPACE aop_index;
CREATE INDEX ix_reports_created ON audit_reports(created_at) TABLESPACE aop_index;

-- OBSERVATIONS
CREATE TABLE observations (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id           NUMBER NOT NULL,
    observation_number  VARCHAR2(100) NOT NULL,
    title               VARCHAR2(500) NOT NULL,
    description         CLOB NOT NULL,
    category            VARCHAR2(255),
    severity            VARCHAR2(50) DEFAULT 'MEDIUM' NOT NULL,
    status              VARCHAR2(50) DEFAULT 'DRAFT' NOT NULL,
    recommendation      CLOB,
    owner_id            NUMBER,
    assigned_by_id      NUMBER,
    due_date            TIMESTAMP WITH TIME ZONE,
    closed_at           TIMESTAMP WITH TIME ZONE,
    closed_by_id        NUMBER,
    created_by_id       NUMBER NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_obs_number UNIQUE (observation_number),
    CONSTRAINT fk_obs_report FOREIGN KEY (report_id) REFERENCES audit_reports(id),
    CONSTRAINT fk_obs_owner FOREIGN KEY (owner_id) REFERENCES users(id),
    CONSTRAINT fk_obs_assigned_by FOREIGN KEY (assigned_by_id) REFERENCES users(id),
    CONSTRAINT fk_obs_closed_by FOREIGN KEY (closed_by_id) REFERENCES users(id),
    CONSTRAINT fk_obs_created_by FOREIGN KEY (created_by_id) REFERENCES users(id),
    CONSTRAINT ck_obs_severity CHECK (severity IN ('CRITICAL','HIGH','MEDIUM','LOW')),
    CONSTRAINT ck_obs_status CHECK (status IN (
        'DRAFT','PENDING_REVIEW','ASSIGNED','IN_PROGRESS','PENDING_VERIFICATION','CLOSED','REJECTED'
    ))
) TABLESPACE aop_data;

CREATE INDEX ix_obs_status ON observations(status) TABLESPACE aop_index;
CREATE INDEX ix_obs_owner ON observations(owner_id) TABLESPACE aop_index;
CREATE INDEX ix_obs_report ON observations(report_id) TABLESPACE aop_index;
CREATE INDEX ix_obs_due ON observations(due_date) TABLESPACE aop_index;
CREATE INDEX ix_obs_status_owner ON observations(status, owner_id) TABLESPACE aop_index;
CREATE INDEX ix_obs_created ON observations(created_at) TABLESPACE aop_index;

-- Race-safe observation number sequence (used by application on Oracle)
CREATE SEQUENCE obs_number_seq
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE
  ORDER;

-- RESPONSES
CREATE TABLE observation_responses (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    observation_id  NUMBER NOT NULL,
    responder_id    NUMBER NOT NULL,
    response_type   VARCHAR2(50) NOT NULL,
    comments        CLOB NOT NULL,
    committed_date  TIMESTAMP WITH TIME ZONE,
    evidence_file   VARCHAR2(1000),
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_resp_obs FOREIGN KEY (observation_id) REFERENCES observations(id) ON DELETE CASCADE,
    CONSTRAINT fk_resp_user FOREIGN KEY (responder_id) REFERENCES users(id),
    CONSTRAINT ck_resp_type CHECK (response_type IN ('RESOLVED','NEED_MORE_TIME','COMMITTED_TIMELINE'))
) TABLESPACE aop_data;

CREATE INDEX ix_resp_obs ON observation_responses(observation_id) TABLESPACE aop_index;
CREATE INDEX ix_resp_created ON observation_responses(created_at) TABLESPACE aop_index;

-- HISTORY / AUDIT TRAIL (append-only via triggers)
CREATE TABLE observation_history (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    observation_id  NUMBER NOT NULL,
    actor_id        NUMBER NOT NULL,
    action          VARCHAR2(100) NOT NULL,
    from_status     VARCHAR2(50),
    to_status       VARCHAR2(50),
    notes           CLOB,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_hist_obs FOREIGN KEY (observation_id) REFERENCES observations(id) ON DELETE CASCADE,
    CONSTRAINT fk_hist_actor FOREIGN KEY (actor_id) REFERENCES users(id)
) TABLESPACE aop_data;

CREATE INDEX ix_hist_obs ON observation_history(observation_id) TABLESPACE aop_index;
CREATE INDEX ix_hist_created ON observation_history(created_at) TABLESPACE aop_index;
CREATE INDEX ix_hist_actor ON observation_history(actor_id) TABLESPACE aop_index;

-- ---------------------------------------------------------------------------
-- Maintain updated_at
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_users_updated
BEFORE UPDATE ON users
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_obs_updated
BEFORE UPDATE ON observations
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

-- ---------------------------------------------------------------------------
-- Immutable audit history: block UPDATE/DELETE from application accounts
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_hist_no_update
BEFORE UPDATE OR DELETE ON observation_history
BEGIN
  RAISE_APPLICATION_ERROR(-20001, 'observation_history is append-only');
END;
/

-- Prevent closed observations from being silently reopened except via status transition
-- (application still enforces workflow; this blocks direct SQL status jumps to CLOSED without closed_at)
CREATE OR REPLACE TRIGGER trg_obs_closed_integrity
BEFORE UPDATE ON observations
FOR EACH ROW
BEGIN
  IF :NEW.status = 'CLOSED' AND :NEW.closed_at IS NULL THEN
    :NEW.closed_at := SYSTIMESTAMP;
  END IF;
  IF :OLD.status = 'CLOSED' AND :NEW.status <> 'CLOSED' THEN
    RAISE_APPLICATION_ERROR(-20002, 'Closed observations cannot be reopened via direct UPDATE');
  END IF;
END;
/
